name: h
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  google_fonts: ^5.0.0
  sizer: ^2.0.15
  shared_preferences: ^2.2.2
  get: ^4.6.6
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.15.8
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  firebase_storage: ^11.5.5
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7+2
  image_cropper: ^1.4.1
  path_provider: ^2.0.13
  flutter_datetime_picker_plus: ^2.1.0
  connectivity_plus: ^5.0.2
  flutter_cache_manager: ^3.3.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/images/